<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>My Search</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<style type="text/css">
body {
    background: #87CEEB url("images/twitter.png") no-repeat right top;
    margin-right: 200px;
}
h2 {
    color: #191970;
}
h2.thick {
    font-weight: bold;
}
img {
	border-width: 0
}

* {
	font-family: 'Helvetica', sans-serif;
}
</style>
</head>
<body>
	<div>
		<h2>Welcome to TwitterSearch</h2>

		<p>
			Click the button below to sign into Twitter by logging in your Twitter credentials.  
			If you are having issues try <a href='./clearsessions.php'>clearing your session</a>.
		</p>

		<hr />
	</div>

	<p>		
		<pre>
        <?php print_r($content); ?>
      </pre>
	</p>
	
</body>
</html>